### ISSUE TITLE
您好，我有意搜到了这个脚本，但是运行报错。

### ISSUE THREAD

**Issue by corsgoo** [kerncoola/JC_CheckIn#2]
您好，请问脚本是通用吗？url是填写登录页面网址还是签到页面网址呢？（两个都试过报错）https://78cloud.pro/auth/login这个页面可以签到，请问可以更新一下脚本吗。。感谢。运行结果如下：
## 开始执行... 2024-05-21 23:21:10

Traceback (most recent call last):
  File "/ql/data/scripts/kerncoola_JC_CheckIn/JC_CheckIn.py", line 36, in <module>
    sendurl = 'http://www.pushplus.plus/send?token=' + SCKEY + '&title=机场签到&content=' + checkin()
                                                                                            ^^^^^^^^^
  File "/ql/data/scripts/kerncoola_JC_CheckIn/JC_CheckIn.py", line 30, in checkin
    response = json.loads(response.text)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

## 执行结束... 2024-05-21 23:21:14  耗时 4 秒

**Comment by kerncoola** [comment]
不通用，你这个用不了。
